import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import { SSRProvider } from "@restart/ui/ssr";
import { AuthUserProvider } from "../contexts/AuthenticationContext";
import Layout from "../layouts/Layout";

function MyApp({ Component, pageProps }) {
  return (
    <SSRProvider>
      <Head>
        <title>Ranqueamento Estâncias SP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicons.png" />
      </Head>
      <AuthUserProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </AuthUserProvider>
    </SSRProvider>
  );
}

export default MyApp;
