import Head from "next/head";
//import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  const [score, setscore] = useState(0);

  useEffect(() => {
    setscore(pontuacao(""));
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Teste</main>

      <footer></footer>
    </div>
  );
}
